[package]
name = "makepad"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]
rand = "*"
serde_json = "*"
syn = "*"

[dependencies.widgets]
path="./widgets"
default-features = false
features=["mtl"]
