[package]
name = "makepad_wasm"
version = "0.1.0"
authors = ["arc"]
edition = "2018"

[lib]
path = "../src/main.rs"
crate-type = ["cdylib"]

[dependencies]
rand = "*"

[dependencies.shui]
path="../shui"
default-features = false
features=["webgl"]
